name: CI Checks

on:[pash]

jobs:
  test-lint:
    name: Lint & Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    steps:
      -name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOKERHUB }}
        password: ${{ secrets.DOKERHUB_TOKEN }}
      -name: Checkout repository
      uses: actions/checkout@v4
      -name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      -name: Lint
        run: docker-compose run --rm app sh -c "flake8 ."
    